general {
    lock_cmd = pidof hyprlock || hyprlock -q
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && systemctl restart fprintd
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 150
    on-timeout = loginctl lock-session
}
