[manager]
keymap = [
    # Navigation
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "h" ], run = "back",     desc = "Go back" },
    { on = [ "l" ], run = "open",     desc = "Open" },

    # The "Enter" and "Open" Keys
    { on = [ "<Enter>" ], run = "open",            desc = "Open the selected files" },
    { on = [ "o" ],       run = "open --interactive", desc = "Open with a menu" },
    
    # Selection & Operations
    { on = [ "space" ], run = "select --state=toggle", desc = "Toggle selection" },
    { on = [ "y" ],     run = "copy",                desc = "Copy selected" },
    { on = [ "x" ],     run = "cut",                 desc = "Cut selected" },
    { on = [ "p" ],     run = "paste",               desc = "Paste selected" },
    { on = [ "d" ],     run = "remove",              desc = "Move to trash" },
    { on = [ "e" ],     run = "unzip %s",              desc = "Extract ZIP" },

    # Search & Help
    { on = [ "/" ], run = "search fd",    desc = "Search files" },
    { on = [ "i" ], run = "help",         desc = "Show help" },
    { on = [ "q" ], run = "quit",         desc = "Quit Yazi" },
]
