[mgr]
# [Parent, Current, Preview] - Preview needs a positive number to exist!
ratio          = [0, 3, 4]
sort_by        = "mtime"
show_hidden    = false
sort_sensitive = false
sort_reverse   = true
sort_dir_first = false

[opener]
edit = [{ run = 'nvim "$@"', block = true,  desc = "Neovim" }]
pdf  = [{ run = 'zathura "$@"', orphan = true, desc = "Zathura" }]
img  = [{ run = 'imv "$@"',     orphan = true, desc = "imv" }]
vid  = [{ run = 'mpv "$@"',     orphan = true, desc = "mpv" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
unzip = [{ run = "unzip %@", block = true, for = "unix", desc = "Extract here" }]
[open]
rules = [
    { mime = "text/*",           use = "edit" },
    { mime = "application/pdf",  use = ["pdf", "open"] },
    { mime = "image/*",          use = ["img", "open"] },
    { mime = "video/*",          use = ["vid", "open"] },
    { mime = "*",                use = "open" },
]
[preview]
cache_dir   = ""
image_delay = 0
max_width   = 1500
max_height  = 1500

[plugin]
previewers = [
    { mime = "inode/directory", run = "folder", sync = true },
    { mime = "text/*",          run = "code" },
    { mime = "image/*",         run = "image" },
    { mime = "video/*",         run = "video" },
    { mime = "application/pdf", run = "pdf" },
    { mime = "*",               run = "file" },
]
